os:
  - linux
  - osx
language: python
cache: pip
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pytest
  - pip install -e .
# command to run tests
script: python -m pytest -p no:warnings -v
notifications:
  email:
    recipients:
      - jessime.kirk@gmail.com
      - dsprague@med.unc.edu
      - mauro_calabrese@med.unc.edu
