__title__ = "seekr"
__description__ = "Count small kmer frequencies in nucleotide sequences."
__url__ = "https://github.com/CalabreseLab/seekr"
__version__ = "2.0.0"
__author__ = "Jessime Kirk, Shuang Li, Luke Ni"
__author_email__ = "shuang9@email.unc.edu"
__license__ = "MIT"
